name: docker image

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  dockerimage:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: msda_switchbox
      context_path: .
      push_readme: README.md
    secrets: inherit
