name: Docker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*.*.*"

jobs:
  # https://github.com/edencehealth/workflows
  image:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    permissions:
      packages: write
    with:
      container_name: msda_switchbox
      dockerhub_org: ""
      push_readme: README.md
    secrets: inherit
